(function(g){var window=this;'use strict';var H3=function(a){a.publish("cardstatechange",a.Lk()&&a.Zo()?1:0)},I3=function(a,b){var c=g.ab(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},ynb=function(a){var b=g.Fs(a);
a=g.Is(a);return new g.us(b.x,b.y,a.width,a.height)},znb=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.gC(a,b,function(){g.hC(e);c.apply(a,arguments)},d)},L3=function(a){a=g.fb(a);
delete J3[a];g.nd(J3)&&K3&&K3.stop()},Bnb=function(){K3||(K3=new g.cv(function(){Anb()},20));
var a=K3;a.isActive()||a.start()},Anb=function(){var a=g.kb();
g.bd(J3,function(b){Cnb(b,a)});
g.nd(J3)||Bnb()},M3=function(a,b,c,d){g.vv.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Cnb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Dnb(a,a.progress);1==a.progress?(a.j=0,L3(a),a.onFinish(),a.vr()):a.isPlaying()&&a.SL()},Dnb=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},Enb=function(a,b){g.zb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},N3=function(a,b,c,d,e){M3.call(this,b,c,d,e);
this.element=a},Fnb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
N3.call(this,a,b,c,d,e)},Gnb=function(a){return Math.pow(a,3)},Hnb=function(a){return 3*a*a-2*a*a*a},Inb=function(a){g.I.call(this);
this.B=a||window;this.j=[]},O3=function(a){return a.baseUrl||null},P3=function(a,b){return g.Dt(g.Qr(a,b),function(c){return!!c})},Jnb=function(a,b,c){function d(pa){var ia=pa.hovercardButton;
if(!ia)return null;ia=ia.subscribeButtonRenderer;if(!ia)return null;var va=f(ia.unsubscribedButtonText),aa=f(ia.subscribedButtonText);if(ia.subscribed){var U=f(ia.subscriberCountWithUnsubscribeText);var La=f(ia.subscriberCountText)}else U=f(ia.subscriberCountText),La=f(ia.subscriberCountWithSubscribeText);var y=null;if(pa.signinEndpoint){y=I3(pa,"signinEndpoint","webNavigationEndpointData","url");if(!y){var ba,Ja;y=null==(Ja=g.V(null==(ba=ia.signInEndpoint)?void 0:ba.commandMetadata,g.B2))?void 0:
Ja.url}if(!y)return null}return va&&(aa||y)?{subscribed:ia.subscribed,subscribeText:va,subscribeCount:U,unsubscribeText:aa,unsubscribeCount:La,enabled:ia.enabled,signinUrl:y,classic:pa.useClassicSubscribeButton}:null}
function e(pa){if(pa){var ia=[],va=pa.videoId;va&&ia.push("v="+va);(va=pa.playlistId)&&ia.push("list="+va);(pa=pa.startTimeSeconds)&&ia.push("t="+pa);return"/watch?"+ia.join("&")}}
function f(pa){if(!pa)return null;var ia=pa.simpleText;return ia?ia:pa.runs?g.Qr(pa.runs,function(va){return va.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,w=!1,A=null,C=null,F=null,G=null,L=null,M=null;if("VIDEO"===h)g.V(l,g.QF)?m=g.V(l,g.QF).url:(M=g.V(l,g.XS),m=e(M)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.V(l,g.QF)?m=g.V(l,g.QF).url:(M=g.V(l,g.XS),m=e(M)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(w=I3(l,"browseEndpoint","browseId"))v=w,m="/channel/"+v;n=!1;q="new";(w=!!b.isSubscribe)?A=d(b):C=f(b.subscribersText)}else"WEBSITE"===h?((F=I3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=I3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=I3(b,"title","accessibility","accessibilityData","label");var R=b.endpoint?b.endpoint.clickTrackingParams:null,
ea="";if(b.metadata){var ma=f(b.metadata);ma&&(ea=ma)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ea,callToAction:f(b.callToAction),tW:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,rE:p,playlistLength:t,channelId:v,subscribeButton:A,subscribersText:C,isSubscribe:w,targetUrl:m||null,P8:n,sessionData:R?{itct:R}:null,kda:q,RC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:P3(b.impressionUrls||[],O3),C8:P3(b.hovercardShowUrls||[],O3),clickUrls:P3(l.loggingUrls||[],O3),visualElement:g.WE(b.trackingParams),productPrice:G,additionalFeesText:L,watchEndpoint:M||null}},Knb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:P3(a.impressionUrls||[],O3),elements:P3(a.elements||[],function(d,e){return Jnb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.WE(a.trackingParams));return c},Lnb=function(a){g.sV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.OR(a)||g.QR(a);this.events=new g.vK(this);g.O(this,this.events);this.events.T(this.player,g.EJ("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.FJ("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Vb);this.events.T(window,"focus",this.zba);this.load();var b=g.If("STYLE");(g.xf("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.Sf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Mnb=function(a){return a.player.getVideoData().Nf?"current":a.Z?"new":"current"},Q3=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},Nnb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Knb(f,Mnb(a))));R3(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.wy;d&&(c.postParams={ad_tracking:d});if(b=g.BUa(b))if(b=g.ne(b),b=g.je(b))a.C=g.wB(b,c)},R3=function(a,b,c){c=void 0===c?!0:c;
a.player.yf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Onb(a);c=[];d=new g.DJ(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.W({I:"div",S:"ytp-ce-shadow"}),g.dU(a.player,a.B.element,4),a.D=new g.dG(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Pnb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.dU(a.player,f.element,4);var h=new g.DJ(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Qnb(a,f,e)}else g.bF(new g.xC("buildEndscreenElement null",
e))}a.player.sf(c);a.Vb()}},Onb=function(a){var b=g.XE(),c=g.YE();
c&&b&&a.endscreen.visualElement&&g.cB(g.jF)(void 0,c,b,a.endscreen.visualElement)},Pnb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ka:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.RC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:S3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:T3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.Av(b.title||"")},xa:b.title},{I:"div",S:b.rE?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
xa:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={I:"div",Ka:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.RC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:S3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:T3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.Av(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={I:"div",Ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.RC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ka:["ytp-ce-channel-title","ytp-ce-link"],X:{href:T3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Av(b.title||"")},xa:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{I:"div",Ka:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],xa:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:S3(b)}]};c=new g.W(c);var d=g.yf(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.pv(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.aW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ka:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.RC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",X:{dir:g.Av(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-website-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-website-goto","ytp-ce-link"],X:{href:T3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:S3(b)},{I:"div",S:"ytp-ce-expanding-icon",X:Rnb(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={I:"div",Ka:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.RC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",X:{dir:g.Av(b.title||"")},xa:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:T3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:S3(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
xa:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.pv(c.element,"ytp-ce-placeholder");return c},S3=function(a){if(a.tW)var b=a.tW.thumbnails;
return Rnb(b?b[b.length-1].url:null)},Rnb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Qnb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.pv(b.element,"ytp-ce-force-expand"),U3(a,c.id,!0)):(g.rv(b.element,"ytp-ce-force-expand"),g.rv(b.element,"ytp-ce-element-hover"),U3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){Snb(a,b,c)});
b.listen("mouseleave",function(){Tnb(a,b,c)});
a.player.U().B||b.listen("click",function(){g.pv(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){Unb(a,c,m)});
b.listen("keypress",function(m){Unb(a,c,m)});
b.listen("focus",function(){Snb(a,b,c)});
b.listen("blur",function(){Tnb(a,b,c)});
b.listen("touchstart",function(){Snb(a,b,c)});
var l=g.Af("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.rv(b.element,"ytp-ce-element-hover");g.rv(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.Af("ytp-sb-subscribe",b.element));d(g.Af("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},Unb=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.ov(d,"ytp-ce-element");){g.ov(d,"subscribe-label")&&Vnb(a,b);
if(g.ov(d,"ytp-ce-channel-subscribe"))return;d=g.Tf(d)}if(!d||g.ov(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Tnb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.kda)Vnb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.ne(T3(a,b.targetUrl)),c=g.je(c),g.KG(c,void 0,b.sessionData);else{var e=g.$R(a.player.U())||a.player.getVideoData().Nf,f=function(){var h=T3(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.hB(h);e&&n&&
(n.v||n.list)?a.player.Lo(n.v,l,n.list,!1,void 0,m||void 0):g.fya(h,l)};
Vnb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},T3=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.gS(a)+b}else return"";return b},Snb=function(a,b,c){g.ov(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.pv(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.cv(function(){g.pv(b.element,"ytp-ce-element-hover")},200)).start():g.pv(b.element,"ytp-ce-element-hover"),V3(a,c.C8),U3(a,c.id,!0))},Tnb=function(a,b,c){g.rv(b.element,"ytp-ce-element-hover");
g.rv(b.element,"ytp-ce-force-expand");U3(a,c.id,!1)},U3=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.uv(a.j[e].element,"ytp-ce-element-shadow-show",c)},V3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||Q3(a))c&&c();else{b=Wnb(a,b);var e=0,f=!1,h=new g.cv(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.RD(b[a],d)}},Vnb=function(a,b,c){V3(a,b.clickUrls,c);
(a=g.YE())&&b.P8&&g.qF(a,b.visualElement)},Wnb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Xnb(b[d],c));return a},Xnb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Ynb=function(a){return"string"===typeof a?a:""},W3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Znb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},X3=function(a){return a.value?a.value:null},Y3=function(a){if(!a)return null;
var b=g.ne(Ynb(a.value));b=g.je(b);if(!b)return null;var c=W3(a.target,$nb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Znb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},aob=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},dob=function(a){if(!a)return null;
var b=W3(a.type,bob),c=W3(a.trigger,cob);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=Y3(a?a:null);return b?new aob(b,c,a):null},eob=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},fob=function(a,b){return g.Db(a.action,b)},gob=function(a,b){this.context=a;
this.j=b},hob=function(a){return a.customMessage?Z3("div","iv-card-message",a.customMessage):""},$3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",X:{style:a},V:c}},iob=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(Z3("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},Z3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Av(c);return{I:a,X:b,xa:c}},job=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.bD&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.bD+");");c.dir=g.Av(a.customMessage);var d=[{I:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ka:b,X:c,V:d}},a4=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.ej.click,5)}},kob=function(a,b){this.merchant=a;
this.price=b},lob=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},mob=function(a,b){return b?b:lob(a)?"current":"new"},b4=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.rb=!1;this.Va=new Map;this.Ya=new Map;this.context.J.addEventListener(g.EJ("annotations_module"),function(d){(d=c.Va.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.FJ("annotations_module"),function(d){(d=c.Ya.get(d))&&d.apply(c)})},c4=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.TL(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.rb=!1});
a.context.j.listen(b,"touchmove",function(){a.rb=!0})},nob=function(a){var b;
return(null==(b=g.V(a,g.QF))?0:b.url)?g.V(a,g.QF).url:(a=g.V(a,g.XS))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},d4=function(a,b,c){return{ZX:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
J0:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
lL:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},oob=function(a,b,c){b4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Fb=this.Ma=this.Jb=this.C=this.isInitialized=!1;this.cards=[];this.wb=this.Z=this.La=this.G=this.Ta=this.j=null;this.oa=[];this.ra=this.N=this.Kf=this.Da=null;this.K=0;this.Ga=new g.cv(function(){},c.W.Kl?4E3:3E3);
g.O(this,this.Ga);this.eb=new g.cv(function(){});
g.O(this,this.eb);this.Ba=new gob(c,function(e,f,h,l,m,n){c4(d,e,f,h,l,m,n)});
this.Y=new g.W({I:"div",S:"iv-drawer",X:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",X:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ka:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.O(this,this.Y);this.D=this.Y.element;this.Za=new g.dG(this.Y,330);g.O(this,this.Za);this.Eb=g.Af("iv-drawer-header-text",this.D);this.B=g.Af("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Jb&&e4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Jb=d.C)&&f4(d)});
this.Qa=new g.vK(this);g.O(this,this.Qa);this.J.addEventListener("videodatachange",this.nt.bind(this))},pob=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){e4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){f4(a)});
var c=b.headerText;g.Vf(a.Eb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Da=g.WE(b.trackingParams);a.N=g.WE(b.closeTrackingParams);a.Kf=g.WE(b.iconTrackingParams)},qob=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.ib("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.EF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,ej:{},hp:null,Mj:e.trackingParams?g.WE(e.trackingParams):null,Kf:f&&f.trackingParams?g.WE(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
bD:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};g4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.EF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:h4(a,c,b,f),sponsored:!1,ej:d4(f,e,f.command),hp:f.trackingParams?g.WE(f.trackingParams):null,Mj:e.trackingParams?g.WE(e.trackingParams):null,Kf:l&&l.trackingParams?g.WE(l.trackingParams):null,imageUrl:i4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.EF(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,bD:null,title:f.title?g.EF(f.title):"",customMessage:f.callToAction?g.EF(f.callToAction):"",url:g.V(f.command,g.QF).url?Y3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(f.command,g.QF).url}):null,onClickCommand:null};g4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.EF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:h4(a,c,b,e),sponsored:!1,ej:d4(e,f,e.endpoint),hp:e.trackingParams?g.WE(e.trackingParams):null,Mj:f.trackingParams?g.WE(f.trackingParams):null,Kf:l&&l.trackingParams?g.WE(l.trackingParams):null,channelId:g.V(e.endpoint,g.lT).browseId,customMessage:e.customText?g.EF(e.customText):null,profileImageUrl:i4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.EF(e.channelName):"",metaInfo:[e.subscriberCountText?g.EF(e.subscriberCountText):""],url:Y3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(e.endpoint,g.lT).canonicalBaseUrl?g.V(e.endpoint,g.lT).canonicalBaseUrl:"/channel/"+g.V(e.endpoint,g.lT).browseId}),onClickCommand:null};g4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.EF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:h4(a,c,b,e),sponsored:!1,ej:d4(e,f,e.action),hp:e.trackingParams?g.WE(e.trackingParams):null,Mj:f.trackingParams?g.WE(f.trackingParams):null,Kf:l&&l.trackingParams?g.WE(l.trackingParams):null,AG:i4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.EF(e.customMessage):null,playlistVideoCount:g.EF(e.playlistVideoCount),title:e.playlistTitle?g.EF(e.playlistTitle):"",metaInfo:[e.channelName?g.EF(e.channelName):
"",e.videoCountText?g.EF(e.videoCountText):""],url:Y3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:nob(e.action)}),onClickCommand:null};g4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.EF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:h4(a,c,b,e),sponsored:!1,ej:d4(e,f,e.action),hp:e.trackingParams?g.WE(e.trackingParams):null,Mj:f.trackingParams?g.WE(f.trackingParams):null,Kf:l&&l.trackingParams?g.WE(l.trackingParams):null,AG:i4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.EF(e.lengthString):null,customMessage:e.customMessage?g.EF(e.customMessage):null,title:e.videoTitle?g.EF(e.videoTitle):"",metaInfo:[e.channelName?g.EF(e.channelName):
"",e.viewCountText?g.EF(e.viewCountText):""],isLiveNow:!!e.badge,url:Y3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:nob(e.action)}),onClickCommand:null};g4(a,b)}}}}}a.K++},i4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},h4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},sob=function(a,b){if(b=rob(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.Ff.id),g.Sf(b.mN),g.Hb(a.cards,b),a.vH(),j4(a)},e4=function(a,b,c){if(!a.C){a.Za.show();
a.Ta=new g.cv(function(){g.pv(a.context.J.getRootNode(),g.cZ.IV_DRAWER_OPEN)},0);
a.Ta.start();a.Qa.T(a.B,"mousewheel",function(h){a.Ga.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.YE();d&&a.Da&&a.N&&g.oF(d,[a.Da,a.N]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.TY||(f.TY=!0,tob(a.context.logger,f.Ff.ej.ZX,b)),d&&g.oF(d,[f.Ff.hp]);H3(a.J);c&&(a.G=new g.cv(function(){a.La=a.Z;a.wb.focus()},330),a.G.start())}},f4=function(a){a.C&&(a.Za.hide(),g.mC(a.Qa),g.rv(a.context.J.getRootNode(),g.cZ.IV_DRAWER_OPEN),a.C=!1,H3(a.J),a.G&&a.G.stop(),a.G=new g.cv(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},vob=function(a){g.qv(a.Hb(),
[g.cZ.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.dU(a.J,a.D,5);uob(a);a.Z=g.Af("ytp-cards-button",a.J.getRootNode());a.wb=g.Af("iv-drawer-close-button",a.D);a.isInitialized=!0},uob=function(a){var b=g.Af("iv-drawer-close-button",a.D);
a.context.j.listen(b,"click",a.n6,a);a.context.j.listen(a.B,"touchend",function(){a.Ga.start()});
a.context.j.listen(a.B,"scroll",a.J6,a);a.context.B.subscribe("onHideControls",function(){a.Ma=!0});
a.context.B.subscribe("onShowControls",function(){a.Ma=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Ma=g.ov(a.J.getRootNode(),"ytp-autohide")});
a.oa.push(g.eE("iv-button-shown",a.i9,a));a.oa.push(g.eE("iv-button-hidden",a.h9,a));wob(a)},wob=function(a){a.oa.push(g.eE("iv-teaser-shown",a.U2,a));
a.oa.push(g.eE("iv-teaser-hidden",a.j9,a));a.oa.push(g.eE("iv-teaser-clicked",a.T2,a));a.Fb=!0},xob=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.V(b.onClickCommand,g.Zjb))?void 0:c.targetId)?(a.ra=b,!0):!1},yob=function(a,b){a.ra=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.aTa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.V(h[0],g.w0a))?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},g4=function(a,b){if(!xob(a,b)||yob(a,b)){var c=zob(a,b);
if(c){var d={Ff:b,mN:c.element,TY:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Fb||wob(a),sob(a,b.id),c=a.findLastIndex(d),g.Pb(a.cards,c,0,d));else{a.isInitialized||vob(a);sob(a,b.id);var e=a.findLastIndex(d);g.Pb(a.cards,e,0,d);c.Ja(a.B,e);a.vH()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,j4(a),Aob(a,d),e4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&Bob(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){Bob(a,d)}),j4(a))}}},zob=function(a,b){switch(b.type){case "simple":a=a.Ba;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=job(b);c={I:"div",Ka:["iv-card"],V:[{I:"a",S:"iv-click-target",X:{href:b.url?X3(b.url)||"":""},V:[$3(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[Z3("h2",void 0,b.title),d]}]}]};c=new g.W(c);a4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ba;c={I:"div",Ka:["iv-card","iv-card-channel"],V:[{I:"a",Ka:["iv-click-target"],X:{href:X3(b.url)||"","data-ytid":b.channelId},V:[$3(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[hob(b),{I:"h2",S:"iv-card-primary-link",xa:b.title},iob(b)]}]}]};c=new g.W(c);a4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ba;c={I:"div",Ka:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",X:{href:X3(b.url)||""},V:[$3(b.AG,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[hob(b),Z3("h2","iv-card-primary-link",b.title),iob(b)]}]}]};
c=new g.W(c);a4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ba;var e=0!=b.offers.length;c=["iv-card"];d="";var f=job(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",xa:f.merchant}),f={I:"div",V:e});e=b.url?X3(b.url)||"":"";c={I:"div",Ka:c,X:{tabindex:"0"},V:[{I:"a",Ka:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",xa:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",X:{href:e},V:[Z3("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.If("span");g.Vf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Od(d,"adInfo");a4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ba;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",xa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ka:["yt-badge","yt-badge-live"],xa:"LIVE NOW"}:null;e={I:"div",Ka:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",X:{href:(null==(c=b.url)?void 0:X3(c))||""},V:[$3(b.AG,d),{I:"div",S:"iv-card-content",V:[hob(b),Z3("h2","iv-card-primary-link",b.title),iob(b),f]}]}]};c=new g.W(e);a4(a,g.zf("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Cob=function(a){if(a.j)return"productListing"===a.j.Ff.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.Rr(a.cards,function(c){return"productListing"===c.Ff.type})}return g.Rr(a.cards,function(c){return"productListing"===c.Ff.type})},j4=function(a){g.uv(a.J.getRootNode(),"ytp-cards-shopping-active",Cob(a))},Bob=function(a,b){if(!g.ov(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.YE(),d=a.j?a.j.Ff.Kf:a.Kf;
c&&d&&g.pF(c,[d]);a.j=b;j4(a)}(c=a.isInitialized&&"none"==a.Hb().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.Ff.teaserDurationMs&&a.J.wB(!0,{teaserText:b.Ff.teaserText,durationMs:b.Ff.teaserDurationMs,onClickCommand:b.Ff.onClickCommand});a.eb.isActive()||((!a.C||!a.Ga.isActive()&&a.Ma)&&Aob(a,b),a.eb.start(910+b.Ff.teaserDurationMs))}},Aob=function(a,b){a.Y.Cb?(b=new M3([0,
a.B.scrollTop],[0,b.mN.offsetTop],600,Hnb),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.AF(a.Y,!0),a.B.scrollTop=b.mN.offsetTop,g.AF(a.Y,!1))},k4=function(a){return a.j&&a.j.Ff?a.j.Ff:a.cards[0]&&a.cards[0].Ff?a.cards[0].Ff:null},rob=function(a,b){return g.Db(a.cards,function(c){return c.Ff.id===b})},l4=function(a,b,c){b4.call(this,a,b);
this.annotation=c;this.isActive=!1},Dob=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},m4=function(a,b,c){l4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Eob=function(a,b){var c=void 0===c?0:c;
var d=ynb(b).width;g.Ds(b,d);c=new Fnb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Gnb);g.O(a,c);a.context.C.listen(c,"begin",function(){g.Js(b,!0)});
c.play()},Hob=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ka:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({I:"div",Ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.aW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ja(d));var f=a.createElement({I:"div",Ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ka:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Js(h,!1);var l=a.createElement({I:"div",Ka:["branding-context-container-outer"]});l.appendChild(h);g.xs(l,"right",b.image_width+"px");g.Kf(a.Hb(),l);a.C=new g.cv(function(){Fob(a,h,l)},500);
g.O(a,a.C);a.context.j.listen(a.Hb(),"mouseover",function(){Gob(a,h,l,f,b.image_height)});
a.context.j.listen(a.Hb(),"mouseout",function(){a.C.start()})}},Gob=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Is(b);a.j||(b.style.width=g.Cs(f.width,!0),c.style.width=g.Cs(f.width,!0));g.xs(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.xs(d,"right","1px");a.D=!0;g.Js(b,!0);a.G=new g.cv(function(){g.pv(this.Hb(),"iv-branding-active")},0,a);
a.G.start()}},Fob=function(a,b,c){g.rv(a.Hb(),"iv-branding-active");
a.K=new g.cv(function(){g.Js(b,!1);a.j||(c.style.width=g.Cs(0,!0))},250);
a.K.start();a.D=!1},Iob=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.W=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},Job=function(a,b,c){l4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ka:["iv-promo-contents"]});this.G=new g.cv(function(){d.j.setAttribute("aria-hidden","true");g.Js(d.C,!1);g.Js(d.B,!0)},700,this);
g.O(this,this.G)},Mob=function(a,b,c){c.stopPropagation();
Kob(a);Lob(a,b);a.j.focus()},Nob=function(a){a.isCollapsed||a.Z||a.D||(g.pv(a.Hb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Kob=function(a){a.G.stop();
a.isCollapsed&&(g.tv(a.Hb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Js(a.B,!1),g.Js(a.C,!0))},Lob=function(a,b){a.D||(a.D=g.Dg(function(){Oob(this);
Nob(this)},b,a))},Oob=function(a){a.D&&(g.Ta.clearTimeout(a.D),a.D=null)},Pob=function(a){this.J=a},tob=function(a,b,c){b&&(c?n4(a,b.map(function(d){return g.Su(d,c)})):n4(a,b))},n4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.RD(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},Qob=function(a){g.sV.call(this,a);
var b=this;this.oa=this.Z=!1;this.loadNumber=0;this.N={};this.logger=new Pob(this.player);this.D=new g.vK(this);this.G=this.K=null;this.events=new g.vK(this);this.Wg=this.Y=this.j=null;this.ra=[];g.O(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.V2,this);this.subscribe("resize",this.ZJ,this);this.player.U().Ma.subscribe("vast_info_card_add",this.YZ,this);g.O(this,this.events);this.Ba=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.W({I:"div",Ka:["ytp-player-content","ytp-iv-player-content"]});g.O(this,this.B);g.dU(this.player,this.B.element,4);this.B.hide();this.C=new g.W({I:"div",Ka:["ytp-iv-video-content"]});g.O(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Ba);this.C.element.appendChild(a);this.mu()&&this.load();var c=this.createElement({I:"style"});(g.xf("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.Sf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Rob=function(a){a=a.createElement({I:"div",
Ka:["annotation","annotation-type-custom"]});g.Js(a,!1);return a},Sob=function(a,b){b=!b.isCued()&&!g.jG(b,1024);
g.AF(a.B,b);g.AF(a.C,b)},Tob=function(a,b,c){a.Z=!0;
a.G=g.wB(b,c)},Uob=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.bb(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Uob(a,e))}return c},Yob=function(a){var b=a.player.getVideoData();
if(b.Ta){var c=a.player.U().Ma.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.pB(h)&&h.responseXML?h.responseXML:null)&&Vob(a,h)}};
g.FC()&&(d.onFinish=Wob(a,d.onFinish));d.postParams={ic_only:"1"};Xob(d,c);a.Z=!0;g.wB(b.Ta,d)}}},Xob=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.BH&&(a.postParams.ic_coll=b.BH);b.nN&&(a.postParams.ic_xml=b.nN);b.qL&&(a.postParams.ic_track=b.qL)},Zob=function(a){var b=new g.W({I:"div"});
g.Js(b.element,!1);var c=new oob(a.player,b.element,o4(a));g.O(c,b);b.Ja(a.B.element);c.jG();return c},apb=function(a,b){var c,d;
if(b=null==(c=b.getWatchNextResponse())?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.oa=!0,$ob(a,b),b.headerText&&a.Wg&&(c=g.EF(b.headerText),a.Wg.setAttribute("title",c))},o4=function(a){if(!a.Y){var b=new Inb(a);
g.O(a,b);var c=new g.Jp(a);g.O(a,c);a.Y=new Iob(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.uj)}return a.Y},Vob=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.YE();if(e){var f=g.XE();f&&g.cB(g.Ewa)(void 0,e,f,[g.WE(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Uob(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=W3(f.type,bpb),p=W3(f.style,cpb),q=Ynb(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=dob;if(null==t)var v=null;else if(g.ab(t)){l=[];for(var w=g.u(t),A=w.next();!A.done;A=w.next()){var C=f(A.value);
C&&l.push(C)}v=l}else{var F=f(t);v=F?[F]:[]}e=m&&n?new eob(m,n,p,v,r):null}else e=null}catch(ma){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var G=Rob(f),L=null;switch(l.type){case "branding":if(f.player.U().Zd)break;f.B.element.appendChild(G);L=new m4(G,o4(f),l);break;case "promotion":g.dU(f.player,G,4),L=new Job(G,o4(f),l)}L&&L.jG();if(f=L)g.O(a,f),a.N[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Zob(a),g.O(a,a.j));if("card"===e.type){G=a.j;var M=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(M)switch(f=e.tracking||{},f={ZX:f.impression,click:f.click,close:f.close,J0:f.teaser_impression,lL:f.teaser_click},l=e.tracking_params||{},L=null,M){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ej:f,hp:l.card?g.WE(l.card):null,Mj:l.teaser?g.WE(l.teaser):null,Kf:l.icon?g.WE(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:Y3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};g4(G,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ej:f,
hp:l.card?g.WE(l.card):null,Mj:l.teaser?g.WE(l.teaser):null,Kf:l.icon?g.WE(l.icon):null,AG:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:Y3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};g4(G,c);break;case "productListing":e.signin_url&&(L=Y3({target:"current",value:e.signin_url}));M=[];for(var R=e.offers||[],ea=0;ea<R.length;ea++)M.push(new kob(g.ef(R[ea].merchant),
g.ef(R[ea].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ej:f,hp:l.card?g.WE(l.card):null,Mj:l.teaser?g.WE(l.teaser):null,Kf:l.icon?g.WE(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,bD:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:Y3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),Opb:L,Npb:e.signin_title?e.signin_title:void 0,Mpb:e.signin_message?e.signin_message:void 0,offers:M,onClickCommand:null};g4(G,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ej:f,hp:l.card?g.WE(l.card):
null,Mj:l.teaser?g.WE(l.teaser):null,Kf:l.icon?g.WE(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,bD:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:Y3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};g4(G,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ej:f,hp:l.card?g.WE(l.card):null,Mj:l.teaser?g.WE(l.teaser):null,Kf:l.icon?g.WE(l.icon):null,AG:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:Y3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},g4(G,c)}}else pob(a.j,e);c=!0}}c&&
(H3(a.player),a.ZJ())},$ob=function(a,b){var c=!1;
a.j||(a.j=Zob(a),g.O(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(qob(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.sT(f)||(c=a.j,d=b.headerText?g.EF(b.headerText):"",g.Vf(c.Eb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Da=b.trackingParams?g.WE(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.WE(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Kf=b.icon.infoCardIconRenderer.trackingParams?g.WE(b.icon.infoCardIconRenderer.trackingParams):null,a.ZJ());H3(a.player)}},dpb=function(a,b,c,d,e){if(!a.player.U().Zd){var f=[];
b.navigationEndpoint&&g.V(b.navigationEndpoint,g.lT)&&g.V(b.navigationEndpoint,g.lT).browseId&&f.push(new aob("openUrl","click",new Znb("/channel/"+g.V(b.navigationEndpoint,g.lT).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.V(b.subscribeButton,
g.mT)){d.channel_id=g.V(b.subscribeButton,g.mT).channelId;var l;b=g.V(b.subscribeButton,g.mT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.EF(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.EF(b.subscriberCountText))):(b.subscriberCountText&&(e=g.EF(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.EF(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.V(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.B2))?void 0:m.url)||"";l={subscribeText:g.EF(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.EF(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new eob(c,"branding","branding",f,d);l=Rob(a);a.B.element.appendChild(l);f=new m4(l,o4(a),f);f.jG();g.O(f,f);a.N[c]=f}},Wob=function(a,b){return function(){var c=g.Ia.apply(0,arguments);
a.isDisposed()||a.ra.push(g.Vu.Qi(function(){b.apply(null,g.qa(c))}))}},epb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.WT.prototype.wB=g.fa(28,function(a,b){var c=g.JV(this.xb());c&&c.wB(a,b)});
var J3={},K3=null;g.lb(M3,g.vv);g.k=M3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;L3(this);this.startTime=a=g.kb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.QJ();this.vn("play");this.isPaused()&&this.vn("resume");this.j=1;var b=g.fb(this);b in J3||(J3[b]=this);Bnb();Cnb(this,a);return!0};
g.k.stop=function(a){L3(this);this.j=0;a&&(this.progress=1);Dnb(this,this.progress);this.onStop();this.vr()};
g.k.pause=function(){this.isPlaying()&&(L3(this),this.j=-1,this.vn("pause"))};
g.k.va=function(){0==this.j||this.stop(!1);this.vn("destroy");M3.Sf.va.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.SL=function(){this.vn("animate")};
g.k.vn=function(a){this.dispatchEvent(new Enb(a,this))};
g.lb(Enb,g.zb);g.lb(N3,M3);N3.prototype.C=function(){};
N3.prototype.SL=function(){this.C();N3.Sf.SL.call(this)};
N3.prototype.vr=function(){this.C();N3.Sf.vr.call(this)};
N3.prototype.QJ=function(){this.C();N3.Sf.QJ.call(this)};
g.lb(Fnb,N3);Fnb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.x(Inb,g.I);g.k=Inb.prototype;g.k.listen=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=g.gC(a,b,c);this.j.push(a);return a};
g.k.rJ=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=znb(a,b,c);this.j.push(a);return a};
g.k.Sc=function(a){g.hC(a);g.Hb(this.j,a)};
g.k.removeAll=function(){g.hC(this.j);this.j.length=0};
g.k.va=function(){this.removeAll();g.I.prototype.va.call(this)};g.x(Lnb,g.sV);g.k=Lnb.prototype;g.k.load=function(){g.sV.prototype.load.call(this);if(!Q3(this)){var a=g.CUa(this.player.getVideoData());a?(a=Knb(a,Mnb(this)),R3(this,a,!1)):Nnb(this)}};
g.k.unload=function(){R3(this,null);this.C&&(this.C.abort(),this.C=null);g.sV.prototype.unload.call(this)};
g.k.Ph=function(a,b){return Q3(this)?"loadCustomEndscreenRenderer"===a?(a=Knb(b,"new"),R3(this,a),!0):null:null};
g.k.getOptions=function(){return Q3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Vb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<fpb.length;f++){var h=Math.abs(b.width-fpb[f]);if(-1===e||d>=h)e=f,d=h}d=gpb[e];this.B&&g.xs(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Hs(e.element,m,f);g.Ds(e.element,n,p);g.tv(e.element,hpb);256<m||256<f?g.pv(e.element,"ytp-ce-large-round"):96<m||96<f?g.pv(e.element,"ytp-ce-medium-round"):g.pv(e.element,"ytp-ce-small-round");g.tv(e.element,ipb);m=h.left+h.width/2;h=h.top+l/2;g.pv(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.tv(e.element,gpb);g.pv(e.element,d);(e=g.yf(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.xs(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())V3(this,this.endscreen.impressionUrls),(a=g.YE())&&this.endscreen.visualElement&&g.nF(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.pv(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.pv(b,"ytp-ce-shown");V3(this,c.impressionUrls);(b=g.YE())&&g.nF(b,c.visualElement);this.player.U().N&&this.player.gb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.rv(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.rv(b,"ytp-ce-shown");this.player.U().N&&this.player.gb("endscreenelementhidden",a)}};
g.k.zba=function(a){var b=this;a.target===window&&(new g.cv(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.tv(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var fpb=[346,426,470,506,570,640,853,1280,1920],gpb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),ipb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],hpb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var $nb={hva:"current",mWa:"new"};var bob={CLOSE:"close",d_a:"openUrl",SUBSCRIBE:"subscribe"},cob={qta:"click",CLOSE:"close",hHa:"hidden",g5a:"rollOut",h5a:"rollOver",X6a:"shown"};eob.prototype.Re=function(){var a=fob(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var cpb={Ina:"anchored",f2:"branding",CHANNEL:"channel",Xua:"cta",kHa:"highlightText",oLa:"label",PLAYLIST:"playlist",POPUP:"popup",Z9a:"speech",SUBSCRIBE:"subscribe",Pcb:"title",VIDEO:"video",rkb:"website"},bpb={f2:"branding",Sqa:"card",hxa:"drawer",jHa:"highlight",ERa:"marker",r3a:"promotion",TEXT:"text",Xlb:"widget"};g.x(b4,g.I);g.k=b4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.DJ(a,b,{id:c,namespace:"annotations_module"});d&&this.Va.set(a,d);e&&this.Ya.set(a,e);this.context.J.sf([a])};
g.k.jG=function(){this.context.B.subscribe("resize",this.vH,this)};
g.k.Hb=function(){return this.element};
g.k.TL=function(a,b,c,d,e,f){if(this.rb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Sf(this.Hb())};
g.k.vH=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=X3(a);if(f){var h=mob(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Nf||!1,n=g.hB(f||"");m&&n&&(n.v||n.list)?e.context.J.Lo(n.v,b,n.list,!1):g.KG(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);n4(this.context.logger,c,l,d);lob(f)||(c=g.YE(),d=b.itct,c&&d&&g.qF(c,g.WE(d)))}};
g.k.va=function(){this.Va.clear();this.Ya.clear();g.I.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.O(this,a);return a.element};g.x(oob,b4);g.k=oob.prototype;g.k.nt=function(){this.ra&&g4(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Is(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.vH=function(){var a=this.isAvailable();g.Js(this.Hb(),a);g.uv(this.context.J.getRootNode(),g.cZ.IV_DRAWER_ENABLED,a);H3(this.J)};
g.k.destroy=function(){this.J.wB(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.fE(this.oa);g.mC(this.Qa);this.Ta&&this.Ta.dispose();this.G&&this.G.dispose();b4.prototype.destroy.call(this)};
g.k.findLastIndex=function(a){if(0===this.cards.length)return 0;var b=g.Eb(this.cards,function(c){return a.Ff.startMs>c.Ff.startMs||a.Ff.startMs===c.Ff.startMs&&a.Ff.timestamp>=c.Ff.timestamp?!0:!1});
return-1===b?0:b+1};
g.k.n6=function(){if(this.C){n4(this.context.logger,k4(this).ej.close);var a=g.YE();a&&this.N&&g.qF(a,this.N);f4(this)}};
g.k.J6=function(){g.uv(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.i9=function(){var a=g.YE(),b=k4(this);b=b?b.Kf:this.Kf;a&&b&&g.oF(a,[b])};
g.k.h9=function(){var a=g.YE(),b=k4(this);b=b?b.Kf:this.Kf;a&&b&&g.pF(a,[b])};
g.k.U2=function(){var a=k4(this);n4(this.context.logger,a.ej.J0);var b=g.YE();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Mj&&c.push(a.Mj);a.Kf&&c.push(a.Kf);0<c.length&&g.oF(b,c)}else g.oF(b,[a.Mj,a.Kf])};
g.k.j9=function(){var a=g.YE(),b=k4(this);a&&b&&g.pF(a,[b.Mj])};
g.k.T2=function(a){var b=k4(this),c=g.YE();this.j?a?(a=this.context.logger,n4(a,b.ej.lL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Mj&&g.qF(c,b.Mj)):(a=this.context.logger,n4(a,b.ej.lL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Kf&&g.qF(c,b.Kf)):(a=this.context.logger,n4(a,b.ej.lL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Kf&&g.qF(c,this.Kf))};g.x(l4,b4);l4.prototype.jG=function(){b4.prototype.jG.call(this);Dob(this)};
l4.prototype.show=function(){b4.prototype.show.call(this);var a=g.YE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.oF(a,[g.WE(b.itct)])};
l4.prototype.hide=function(){b4.prototype.hide.call(this);var a=g.YE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.pF(a,[g.WE(b.itct)])};g.x(m4,l4);m4.prototype.yx=function(){g.pv(this.Hb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ka:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Js(this.B,!1);var b=this.createElement({I:"button",Ka:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Hb().appendChild(b);var c=this.annotation.Re();c&&c4(this,b,c,this.annotation.id,a.session_data);Hob(this,a)};
m4.prototype.show=function(){if(!this.isActive&&(l4.prototype.show.call(this),this.N||(this.yx(),this.N=!0),g.Js(this.Hb(),!0),this.isActive=!0,this.B)){try{Eob(this,this.B)}catch(a){}g.pv(this.context.J.getRootNode(),"ytp-branding-shown")}};
m4.prototype.hide=function(){this.isActive&&(l4.prototype.hide.call(this),g.Js(this.Hb(),!1),this.isActive=!1,g.rv(this.context.J.getRootNode(),"ytp-branding-shown"))};
m4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);l4.prototype.destroy.call(this)};g.x(Job,l4);g.k=Job.prototype;
g.k.yx=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Hb().setAttribute("aria-hidden","true");this.Hb().setAttribute("aria-label","Promotion");this.Hb().tabIndex=0;var e=this.annotation.Re(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ka:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&c4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Pe(f,X3(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ka:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ka:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",xa:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&c4(this,
this.Hb(),e,this.annotation.id,b.session_data,void 0,c)}g.pv(this.j,"iv-click-target");e&&c4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",xa:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ka:["yt-badge","iv-promo-badge-live"],xa:"LIVE NOW"})),g.pv(this.j,"iv-click-target"),e&&c4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ka:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.listen(this.B,"click",function(q){Mob(a,5E3,q)});
c.appendChild(this.B);g.Js(this.B,!1);this.context.j.listen(this.Hb(),"mouseover",this.d8,this);this.context.j.listen(this.Hb(),"mouseout",this.c8,this);this.context.j.listen(this.Hb(),"touchend",function(q){Mob(a,5E3,q)});
this.C=this.createElement({I:"button",Ka:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.listen(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.Y7:this.X7,this);c.appendChild(this.C);g.qv(this.Hb(),d);h&&(g.Kf(this.Hb(),h),n&&h.appendChild(n));g.Kf(this.Hb(),this.N);g.Kf(this.Hb(),c)};
g.k.show=function(){this.isActive||(l4.prototype.show.call(this),this.Y||(this.yx(),this.Y=!0),g.Js(this.Hb(),!0),g.Dg(function(){g.rv(this.Hb(),"iv-promo-inactive")},100,this),this.Hb().removeAttribute("aria-hidden"),this.isActive=!0,Oob(this),Kob(this),Lob(this,this.K))};
g.k.hide=function(){this.isActive&&(g.pv(this.Hb(),"iv-promo-inactive"),this.isActive=!1,this.Hb().setAttribute("aria-hidden","true"))};
g.k.TL=function(a,b,c,d,e,f){return this.isCollapsed?!1:l4.prototype.TL.call(this,a,b,c,d,e,f)};
g.k.d8=function(a){this.Z=!0;Mob(this,500,a)};
g.k.c8=function(){this.Z=!1;Nob(this)};
g.k.X7=function(a){a.stopPropagation();this.hide()};
g.k.Y7=function(a){a.stopPropagation();Oob(this);this.isCollapsed=!0;g.pv(this.Hb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();l4.prototype.destroy.call(this)};g.x(Qob,g.sV);g.k=Qob.prototype;g.k.Ph=function(a,b){if(!epb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.h2(b))&&Vob(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(sob(this.j,b),H3(this.player)),!0}return null};
g.k.getOptions=function(){return epb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.mu=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.FT(b)||g.PT(this.player.app)?!1:1===c&&!b.qW||a.Ma.get(b.videoId)||g.tT(b)||g.DUa(b)?!0:!1};
g.k.ZJ=function(){if(this.C){var a=this.player.kb().getVideoContentRect(!0);g.Hs(this.C.element,a.width,a.height);g.Ds(this.C.element,a.left,a.top)}if(this.j){var b=this.player.En();a=this.j;b=b.width;g.uv(a.D,"iv-drawer-small",426>=b);g.uv(a.D,"iv-drawer-big",1280<=b)}};
g.k.V2=function(a){Sob(this,a.state);g.jG(a.state,2)&&(this.Lk()&&this.Zo()&&2!==this.player.getPresentingPlayerType()&&this.xB(!1),this.wB(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.pB(h)&&h.responseXML?h.responseXML:null)&&(Vob(b,h),g.pv(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.sV.prototype.load.call(this);Sob(this,this.player.Tb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.FC()&&(a=Wob(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Ma.get(d);f&&Xob(e,f);f=f&&(f.nN||f.BH);if(!c.Ku||f)c.Ta?Tob(this,c.Ta,e):(this.K=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.sT(h))&&!b.oa&&apb(b,h)},this.player.addEventListener("videodatachange",this.K));
g.dU(this.player,this.C.element,4);this.ZJ();(f=g.tT(c))&&$ob(this,f);(f=g.DUa(c))&&f.featuredChannel&&dpb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Wg=g.Af("ytp-cards-button",this.player.getRootNode());g.sT(c)&&apb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ta&&Tob(this,b.Ta,a)};
g.k.unload=function(){this.player.yf("annotations_module");for(var a=g.u(Object.keys(this.N)),b=a.next();!b.done;b=a.next())this.N[b.value].destroy();this.Y=null;this.j&&(this.j.destroy(),this.j=null,H3(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.oa=!1;this.N={};this.B.hide();g.sV.prototype.unload.call(this);this.C.detach();this.K&&(this.player.removeEventListener("videodatachange",this.K),this.K=null)};
g.k.YZ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Yob(this):this.load())};
g.k.Lk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.oa};
g.k.Zo=function(){return!!this.j&&this.j.C};
g.k.xB=function(a,b,c){b=void 0===b?!1:b;this.Lk();this.j&&(a?c?e4(this.j,c,b):e4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):f4(this.j))};
g.k.wB=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.va=function(){this.player.U().Ma.unsubscribe("vast_info_card_add",this.YZ,this);g.rv(this.player.getRootNode(),g.cZ.IV_DRAWER_OPEN);for(var a=this.ra,b=g.Vu,c=0,d=a.length;c<d;c++)b.Sj(a[c]);this.ra.length=0;g.sV.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.O(this,a);return a.element};g.rV("annotations_module",Qob);g.rV("creatorendscreen",Lnb);})(_yt_player);
