(function(g){var window=this;'use strict';var Fub=function(a,b){g.W.call(this,{I:"button",Ka:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],X:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},V:[{I:"svg",X:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},V:[{I:"g",X:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},V:[{I:"g",X:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
V:[{I:"path",X:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.J=a;this.listen("click",this.onClick,this);this.updateValue("title",g.VT(a,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.TT(b.Qe(),this.element))},Gub=function(a){g.W.call(this,
{I:"div",
S:"ytp-miniplayer-ui"});this.G=!1;this.player=a;this.T(a,"minimized",this.kh);this.T(a,"onStateChange",this.z3)},Hub=function(a){g.sV.call(this,a);
this.B=new g.vK(this);this.j=new Gub(this.player);this.j.hide();g.dU(this.player,this.j.element,4);a.isMinimized()&&(this.load(),g.uv(a.getRootNode(),"ytp-player-minimized",!0))};
g.x(Fub,g.W);Fub.prototype.onClick=function(){this.J.gb("onExpandMiniplayer")};g.x(Gub,g.W);g.k=Gub.prototype;
g.k.show=function(){this.j=new g.av(this.x3,null,this);this.j.start();if(!this.G){this.tooltip=new g.EX(this.player,this);g.O(this,this.tooltip);g.dU(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.ke=new g.XV(this.player);g.O(this,this.ke);this.B=new g.W({I:"div",S:"ytp-miniplayer-scrim"});g.O(this,this.B);this.B.Ja(this.element);this.T(this.B.element,"click",this.wT);var a=new g.W({I:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},V:[g.IF()]});g.O(this,
a);a.Ja(this.B.element);this.T(a.element,"click",this.vT);a=new Fub(this.player,this);g.O(this,a);a.Ja(this.B.element);this.C=new g.W({I:"div",S:"ytp-miniplayer-controls"});g.O(this,this.C);this.C.Ja(this.B.element);this.T(this.C.element,"click",this.wT);var b=new g.W({I:"div",S:"ytp-miniplayer-button-container"});g.O(this,b);b.Ja(this.C.element);a=new g.W({I:"div",S:"ytp-miniplayer-play-button-container"});g.O(this,a);a.Ja(this.C.element);var c=new g.W({I:"div",S:"ytp-miniplayer-button-container"});
g.O(this,c);c.Ja(this.C.element);this.N=new g.RW(this.player,this,!1);g.O(this,this.N);this.N.Ja(b.element);b=new g.QW(this.player,this);g.O(this,b);b.Ja(a.element);this.nextButton=new g.RW(this.player,this,!0);g.O(this,this.nextButton);this.nextButton.Ja(c.element);this.K=new g.xX(this.player,this);g.O(this,this.K);this.K.Ja(this.B.element);this.progressBar=new g.WW(this.player,this);g.O(this,this.progressBar);g.dU(this.player,this.progressBar.element,4);this.D=new g.W({I:"div",S:"ytp-miniplayer-buttons"});
g.O(this,this.D);g.dU(this.player,this.D.element,4);a=new g.W({I:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},V:[g.IF()]});g.O(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.vT);a=new g.W({I:"button",Ka:["ytp-miniplayer-replay-button","ytp-button"],X:{"aria-label":"Close"},V:[g.mxa()]});g.O(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.yaa);this.T(this.player,"presentingplayerstatechange",this.y3);this.T(this.player,"appresize",this.Vb);
this.T(this.player,"fullscreentoggled",this.Vb);this.Vb();this.G=!0}0!==this.player.getPlayerState()&&g.W.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.j&&(this.j.dispose(),this.j=void 0);g.W.prototype.hide.call(this);this.player.isMinimized()||(this.G&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.k.va=function(){this.j&&(this.j.dispose(),this.j=void 0);g.W.prototype.va.call(this)};
g.k.vT=function(){this.player.stopVideo();this.player.gb("onCloseMiniplayer")};
g.k.yaa=function(){this.player.playVideo()};
g.k.wT=function(a){if(a.target===this.B.element||a.target===this.C.element)g.oL(this.player.Tb())?this.player.pauseVideo():this.player.playVideo()};
g.k.kh=function(){g.uv(this.player.getRootNode(),"ytp-player-minimized",this.player.isMinimized())};
g.k.cg=function(){this.progressBar.Rc();this.K.Rc()};
g.k.x3=function(){this.cg();this.j&&this.j.start()};
g.k.y3=function(a){g.jG(a.state,32)&&this.tooltip.hide()};
g.k.Vb=function(){g.l1a(this.progressBar,0,this.player.kb().getPlayerSize().width,!1);g.XW(this.progressBar)};
g.k.z3=function(a){this.player.isMinimized()&&(0===a?this.hide():this.show())};
g.k.Qe=function(){return this.tooltip};
g.k.Xt=function(a,b,c,d,e){var f=0,h=d=0,l=g.Is(a);if(b){c=g.ov(b,"ytp-prev-button")||g.ov(b,"ytp-next-button");var m=g.ov(b,"ytp-play-button"),n=g.ov(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.Gs(b,this.element),h=b.x,f=b.y-12):n&&(h=g.ov(b,"ytp-miniplayer-button-top-left"),f=g.Gs(b,this.element),b=g.Is(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.kb().getPlayerSize().width;e=f+(e||0);l=g.Ie(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};g.x(Hub,g.sV);g.k=Hub.prototype;g.k.onVideoDataChange=function(){if(this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.uv(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.sV.prototype.create.call(this);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.yl=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.rV("miniplayer",Hub);})(_yt_player);
